### ISSUE TITLE
[nitro 2:15:56 pm]  ERROR  Error: Could not load file:///projectpath/.nuxt/feedme.mjs (imported by node_modules/nuxt-feedme/dist/runtime/feedme.mjs)

### ISSUE THREAD

**Issue by Zlatex** [helltraitor/nuxt-feedme#2]
Is there a specific reason why you use fileUrl funtion?
https://github.com/helltraitor/nuxt-feedme/blob/823d2e0f78c65816679266ed8c6e48acd391d3ff/src/module.ts#L40
Because I get this error (in the title) when I do the build, but if I remove the fileUrl and just leave `nuxt.options.alias['#feedme'] = feedme.dst`, everything works fine.

**Comment by helltraitor** [comment]
Yes, I was having troubles with build on Windows. On my Windows machine, such line will give the next error:
```
[worker reload] [worker init] Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 's:'
```

The thing is, this solution must work. I can have check if path begin with non slash symbol, but for now I'm not sure is this solution is good enough. So I will be thinking about possible solutions, but I need more information from you.

Can you give me more information about your setup?

Also, try to inject `console.log` in this way:
```
103 | });
104 | console.log(feedme.dst, fileUrl(feedme.dst), fileUrl(feedme.dst, { resolve: true }), resolver.resolve(feedme.dst));
105 | nuxt.options.alias["#feedme"] = fileUrl(feedme.dst);
106 | nuxt.hook("nitro:config", (config) => {
```
And give me the output from the console (terminal).

And the last one, tell me about your system and node version. This module was develop under 20+

**Comment by Zlatex** [comment]
Here's what I got on Mac:
`/Users/zlatex/boilerplate/.nuxt/feedme.mjs file:///Users/zlatex/boilerplate/.nuxt/feedme.mjs file:///Users/zlatex/boilerplate/.nuxt/feedme.mjs /Users/zlatex/boilerplate/.nuxt/feedme.mjs`

on linux:
`/home/zlatex/projects/boilerplate/.nuxt/feedme.mjs file:///home/zlatex/projects/boilerplate/.nuxt/feedme.mjs file:///home/zlatex/projects/boilerplate/.nuxt/feedme.mjs /home/zlatex/projects/boilerplate/.nuxt/feedme.mjs`

(I get the same error on mac and linux)

My node version is 18.x.x, nuxt - 3.6.5

Also why just don't use runtime config to store this data?

**Comment by helltraitor** [comment]
> My node version is 18.x.x, nuxt - 3.6.5

Can you use node 20+? I use `20.3.1` - some older versions don't support `file://` scheme (but must).

> Also, why don't you just use runtime config to store this data?

As far I know, it's not possible to pass nuxt app into nitro which is used for both SSR\SSG and runtime.

You can take a look on nitro config hook - https://github.com/helltraitor/nuxt-feedme/blob/main/src/module.ts#L46
...and nitro plugin - https://github.com/helltraitor/nuxt-feedme/blob/main/src/runtime/handler.ts

Please, close issue, reply me, or give emoji reaction to this comment if all will be worked after node update

**Comment by Zlatex** [comment]
node 18 is the current recommended version, so I think you must have support for it, as some packages may not support node 20 (this is the case for my project, some of my dependencies don't support node 20), but I tried to build the playground with node 20 and got the same error.

> As far I know, it's not possible to pass nuxt app into nitro which is used for both SSR\SSG and runtime.
You can use runtime config inside nitro app

I've made 2 different fixes that you can check out and choose whatever you like more
https://github.com/Zlatex/nuxt-feedme/commit/d87a2866153eb1d84beb5ba21265610730eb1934
https://github.com/Zlatex/nuxt-feedme/commit/7d19178c080f75f0428a83ba06293834fbd1aebb

**Comment by Zlatex** [comment]
Or maybe `resolver.resolve(feedme.dst)` works for you?

**Comment by helltraitor** [comment]
> Or maybe `resolver.resolve(feedme.dst)` works for you?

Not on Windows.

> node 18 is the current recommended version, so I think you must have support for it, as some packages may not support node 20 (this is the case for my project, some of my dependencies don't support node 20), but I tried to build the playground with node 20 and got the same error.

I tried on Windows, WSL, and Ubuntu LTS 22.04 (VirtualBox) - node 18, node 20 can build my blog site which uses `nuxt-feedme`. So now I sure that problem is specific for you.

I saw you commits, and the next one I like more [d87a286](https://github.com/Zlatex/nuxt-feedme/commit/d87a2866153eb1d84beb5ba21265610730eb1934). But I need to preform some checks (like SSR support) for this change.

**Comment by helltraitor** [comment]
UPD:
Sorry, now, when I started to clean cache and update some extensions (new preview for Typescript arrived). I started to see errors. And ALSO your 🤔
